CREATE TABLE "refusal_forms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"league_event" varchar(255),
	"type" varchar(100),
	"location" varchar(255),
	"incident" varchar(255),
	"patient_name" varchar(255),
	"dob" date,
	"age" uuid,
	"landline" varchar(20),
	"cell" varchar(20),
	"guardian" boolean DEFAULT true,
	"guardian_landline" varchar(20),
	"guardian_cell" varchar(20),
	"guardian_name" varchar(255),
	"guardian_age" uuid,
	"relationship" varchar(100),
	"situation" text,
	"treatment_refused" text,
	"treatment_not_necessary" boolean DEFAULT false,
	"refuses_transport_against_advice" boolean DEFAULT false,
	"treatment_received_no_transport" boolean DEFAULT false,
	"alternative_transportation" boolean DEFAULT false,
	"accepts_transport_refuses_treatment" boolean DEFAULT false,
	"company" varchar(255),
	"pcr" varchar(100),
	"form_date" date,
	"form_time" time,
	"patient_guardian_signature_image" text,
	"patient_guardian_signature_name" varchar(255),
	"events_organizer_signature_image" text,
	"events_organizer_signature_name" varchar(255),
	"witness_signature_image" text,
	"witness_signature_name" varchar(255),
	"medic_personnel_signature_image" text,
	"medic_personnel_signature_name" varchar(255),
	"created_by" uuid,
	"updated_by" uuid
);
--> statement-breakpoint
ALTER TABLE "refusal_forms" ENABLE ROW LEVEL SECURITY;