CREATE TABLE "advance_directives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"patient_first_name" varchar(100) NOT NULL,
	"patient_middle_name" varchar(100),
	"patient_last_name" varchar(100) NOT NULL,
	"patient_age" varchar(10),
	"patient_sex" varchar(10),
	"patient_birthdate" date,
	"patient_citizenship" varchar(100),
	"patient_address" varchar(200),
	"patient_contact_no" varchar(20),
	"next_of_kin_name" varchar(100),
	"next_of_kin_relation" varchar(50),
	"next_of_kin_contact_no" varchar(20),
	"next_of_kin_address" varchar(200),
	"medical_record_number" varchar(50),
	"medical_record_date_accomplished" date,
	"attempt_cpr" boolean DEFAULT false,
	"comfort_only" boolean DEFAULT false,
	"limited_intervention" boolean DEFAULT false,
	"iv_fluid" boolean DEFAULT false,
	"ng_tube" boolean DEFAULT false,
	"o2_therapy" boolean DEFAULT false,
	"cpap_bipap" boolean DEFAULT false,
	"antibiotics" boolean DEFAULT false,
	"diagnostics" boolean DEFAULT false,
	"full_treatment" boolean DEFAULT false,
	"additional_orders" text,
	"discussed_with_patient" boolean DEFAULT false,
	"discussed_with_kin" boolean DEFAULT false,
	"decision_maker_name" varchar(100),
	"decision_maker_relation" varchar(50),
	"decision_maker_date_signed" date,
	"decision_maker_signature" varchar(10000),
	"physician_name" varchar(100),
	"physician_prc_license_number" varchar(50),
	"physician_date_signed" date,
	"physician_signature" varchar(10000),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
