CREATE TABLE "conduction_refusal_forms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"patient_first_name" varchar(100),
	"patient_middle_name" varchar(100),
	"patient_last_name" varchar(100),
	"patient_age" varchar(3),
	"patient_sex" varchar(20),
	"patient_birthdate" date,
	"patient_citizenship" varchar(100),
	"patient_address" text,
	"patient_contact_no" varchar(50),
	"kin_name" varchar(200),
	"kin_relation" varchar(100),
	"kin_contact_no" varchar(50),
	"kin_address" text,
	"medical_record" varchar(100),
	"date_accomplished" date,
	"vital_bp" varchar(20),
	"vital_pulse" varchar(20),
	"vital_resp" varchar(20),
	"vital_skin" varchar(50),
	"vital_pupils" varchar(50),
	"vital_loc" varchar(50),
	"oriented_person_place_time" boolean DEFAULT false,
	"coherent_speech" boolean DEFAULT false,
	"hallucinations" boolean DEFAULT false,
	"suicidal_homicidal_ideation" boolean DEFAULT false,
	"understands_refusal_consequences" boolean DEFAULT false,
	"narrative_description" text,
	"refused_treatment_and_transport" boolean DEFAULT false,
	"refused_treatment_willing_transport" boolean DEFAULT false,
	"wants_treatment_refused_transport" boolean DEFAULT false,
	"witness_name" varchar(200),
	"witness_date" date,
	"witness_signature_image" text,
	"form_status" varchar(20) DEFAULT 'draft',
	"completed_by" uuid
);
--> statement-breakpoint
ALTER TABLE "advance_directives" ALTER COLUMN "decision_maker_signature" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "advance_directives" ALTER COLUMN "physician_signature" SET DATA TYPE varchar(255);