CREATE TABLE "dispatch_forms" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event_title" text,
	"event_type" text,
	"event_owner" text,
	"event_owner_contact" text,
	"event_organizer" text,
	"event_organizer_contact" text,
	"event_date_time" text,
	"event_duration" text,
	"event_call_time" text,
	"estimated_crowd" text,
	"event_venue" text,
	"type_of_events" text,
	"venue_type" text,
	"brief_concept_description" text,
	"expected_vip_guest" text,
	"crowd_access" text,
	"crowd_security" text,
	"crowd_risk" text,
	"crowd_others" text,
	"economic_class" text,
	"crowd_type" text,
	"venue_safety_equipment" text,
	"type_of_service" text,
	"type_of_service_other" text,
	"crew_credential" text,
	"crew_credential_other" text,
	"number_of_crew" text,
	"ambulance_models" jsonb DEFAULT '[]'::jsonb,
	"md_names" jsonb DEFAULT '[]'::jsonb,
	"point_of_destinations" jsonb DEFAULT '[]'::jsonb,
	"special_consideration" text,
	"treated_trauma" integer DEFAULT 0,
	"treated_medical" integer DEFAULT 0,
	"treated_rate_1" text,
	"treated_rate_2" text,
	"treated_waiver" text,
	"transported_trauma" integer DEFAULT 0,
	"transported_medical" integer DEFAULT 0,
	"transported_rate_1" text,
	"transported_rate_2" text,
	"transported_insurance" text,
	"refused_trauma" integer DEFAULT 0,
	"refused_medical" integer DEFAULT 0,
	"refused_rate_1" text,
	"refused_rate_2" text,
	"refused_pre_med_check" text,
	"dispatch_hrs" text,
	"dispatch_min" text,
	"dispatch_reading" text,
	"on_scene_hrs" text,
	"on_scene_min" text,
	"on_scene_reading" text,
	"departure_hrs" text,
	"departure_min" text,
	"departure_reading" text,
	"arrival_hrs" text,
	"arrival_min" text,
	"arrival_reading" text,
	"working_time_hrs" text,
	"working_time_min" text,
	"travel_time_hrs" text,
	"travel_time_min" text,
	"overall_hrs" text,
	"overall_min" text,
	"team_leader_signature" text,
	"client_representative_signature" text,
	"ems_supervisor_signature" text,
	"page3_event_title" text,
	"page3_total_crew" integer,
	"crew_data" jsonb DEFAULT '[]'::jsonb,
	"page3_team_leader_signature" text,
	"page3_client_representative_signature" text,
	"page3_ems_supervisor_signature" text,
	"form_status" varchar(20) DEFAULT 'draft',
	"current_page" integer DEFAULT 1
);
